server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        # proxy to user-service
        - id: user-service
          uri: http://user-service:8081
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1

        # proxy to order-service
        - id: order-service
          uri: http://order-service:8082
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1

        # proxy to product-service
        - id: product-service
          uri: http://product-service:8083
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

# ⭐ Single Swagger UI that shows all three microservices’ OpenAPI docs
springdoc:
  swagger-ui:
    urls:
      - name: user-service
        url: /user-service/v3/api-docs
      - name: order-service
        url: /order-service/v3/api-docs
      - name: product-service
        url: /product-service/v3/api-docs
